import React, { useEffect } from "react";

function Terms () {
    return (
      <div>
<p>TERMS AND CONDITIONS</p>
<p>ALL PRODUCTS ARE MANUFACTURED OR ASSEMBLED IN MELBOURNE AUSTRALIA. WE LIMIT THE AMOUNT OF STOCK FOR EACH PRODUCT, IN ORDER TO KEEP A HEALTHY CYCLE OF PRODUCING THE TOP QUALITY INDIVIDUALLY HANDMADE DESIGNS, AS WELL AS CONTRIBUTING TO SUSTAINABLE FASHION WITH ZERO DEAD STOCK PIECES.</p>
<p>WE DO NOT BELIEVE IN SEASONAL COLLECTION, AS CREATIVITY IS AN ORGANIC FORCE THAT DOES NOT FOLLOW A STRUCTURED PATTERN. THIS MEANS COLLECTIONS ARE RELEASED WITHOUT FORECASTING.</p>
<p>PRIVACY</p>
<p>WE RESPECT YOUR CONCERNS ABOUT PRIVACY AND FOLLOWS STRICT MEASURES TO PROTECT THE CUSTOMER’S INFORMATION AND ENSURE THAT YOUR PERSONAL INFORMATION IS HANDLED RESPONSIBLY.</p>
<p>ALL THE INFORMATION YOU PROVIDE ON THIS WEBSITE IS ONLY TO BE USED TO COMPLETE THE PURCHASE. WE ARE THE SOLE OWNERS OF ALL THE INFORMATION COLLECTED. WE ONLY HAVE ACCESS TO THE INFORMATION YOU INFORM US DIRECTLY. CLIENTS CREDIT CARD INFORMATIONS WILL NOT BE COLLECTED FROM OUR END. WE DO NOT DISCLOSE OUR CLIENT’S NAMES, ADDRESSES, EMAIL ADDRESSES OR OTHER PERSONAL INFORMATIONS. TELEPHONE NUMBERS AND POSTAL ADDRESSES ARE USED FOR PROCESSING ORDERS, DELIVERING PRODUCTS, OBTAINING INFORMATION AND WHEN COMMUNICATION IS NEEDED DIRECTLY TO THE CUSTOMER RELATING TO ORDERS OR ENQUIRIES PLACED THROUGH OUR SITE.</p>
<p>IN ORDER TO ENHANCE OUR ONLINE SERVICE TO CUSTOMERS, COOKIES AND IP ADDRESSES TRACKER ARE USED TO EVALUATE THE RECORDS OF VISITING FREQUENCY, COLLECT DATA INCLUDING YOUR IP ADDRESS, BROWSER TYPE, INTERNET SERVICE PROVIDER, REFERRING/EXIT PAGES, AND DATE/TIME STAMPS. THESE THIRD PARTIES ARE AGREED TO BE ALLOWED TO PROCESS ONLINE DATAS BY YOU(VISITOR) WHEN USING OUR SITE. ALL CLIENT INFORMATION COLLECTED FROM THE WEBSITE WILL NOT BE SHARED WITH THIRD PARTIES.</p>
<p>YOU ACCEPT THAT DATA TRANSMISSION ONLINE CANNOT BE GUARANTEED TO BE SECURE FROM ACCESS BY ILLEGAL RECIPIENTS. YOU AGREE TO HOLD ALL RESPONSIBILITY OF THE DATA TRANSMISSION BY GIVING US ACCESS TO YOUR PERSONAL INFORMATION ONLINE WHILE WE PRACTICE APPROPRIATE SECURITY MEASURES TO PROTECT YOUR PRIVACY. BY USING OUR WEBSITE AND PURCHASE THROUGH ONLINE STORE, YOU ARE AGREEING TO ALL TERMS AND CONDITIONED LISTED ABOVE.</p>
<p>OR ANY GENERAL INQUIRIES REGARDING TO ORDERS AND WEB STORE, PLEASE CONTACT US VIA&nbsp;<a href="mailto:patrickthegu@gmail.com">PATRICKTHEGU@GMAIL.COM</a></p>
</div>

    );
  };
  
  export default Terms;
  